apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
data:
  redis-host: <redis-host> # base64 encoded host
  redis-port: <redis-port> # base64 encoded port
  redis-username: <redis-username> # base64 encoded username
  redis-password: <redis-password> # base64 encoded password
